### ISSUE TITLE
Possible memory leak?

### ISSUE THREAD

**Issue by mmedinajiem** [githubharald/CTCWordBeamSearch#5]
Hi!

I've been trying your code and it works very well. I just have been experiencing an issue that maybe you can shed a light on.

I'm working on handwriting recognition, and when I run my program that eventually uses yours (loaded TFWordBeamSearch.so in Python), but after an almost certain number of processed images (around 250), memory gets full and the process ends with exit code 137. I noticed that memory usage goes up and was wondering if there's something happening (or something I can do) on the cpp side to avoid this behavior.

I'll appreciate any hints.

Thank you!

**Comment by githubharald** [comment]
Hi,

two questions:
1. which mode (Words, NGrams, NGramsForecast, NGramsForecastAndSample) do you use?
2. how often do you call module.word_beam_search(...)? (it should be called only once when creating the TF graph)

Expected behaviour of memory consumption of C++ code: when you call module.word_beam_search(...), the constructor of TFWordBeamSearch (see TFWordBeamSearch.cpp) is called and memory is allocated for the complete lifetime (e.g. for the prefix tree and for the language model). When you evaluate your TF graph with sess.run(decode, { mat:feedMat }), this calls Compute(...) (see TFWordBeamSearch.cpp). This applies the algorithm wordBeamSearch(...) (see WordBeamSearch.cpp) to the data, but it should only allocate temporary memory. 

I had a quick check on the memory consumption for my HTR system for the modes NGrams and NGramsForecast, but it stayed more or less constant.
Let me know if you spot the problem or if you need further help.

Regards
Harry

**Comment by mmedinajiem** [comment]
Hi!

Thank you for your quick reply. Really appreciate it.

Answering your questions:

1) Words only for the time being. 
2) Once per every image I have in the batch. I reshape the numpy arrays to [t, 1, c] for each image. Reading the paper I realized that you can send [t, n, c] where n is the number of samples in the whole batch. There are time where I may have a lot (and I mean a lot) of images to decode and maybe I will have to split them in smaller batches.

Let me try that and I'll get back to you.

Regards!

Manuel

**Comment by githubharald** [comment]
Hi,

1. Regarding the memory leak:
if I understand correctly, you call ```module.word_beam_search(mat, beamWidth, lmType, lmSmoothing, corpus, chars, wordChars)``` for each sample? This would explain the memory leak. 
You should call this function only once. 
It's ok if the size of the input changes between samples. 
You only have to indicate that it's 3d-shaped, so it's enough to pass a placeholder with size ```[None, None, None]``` to ```module.word_beam_search(...)```.
Then, go through your data and pass each matrix to the decode operation with ```res=sess.run(decode, { mat:sample })```. The following code shows how this works.

````
# load custom TF op
word_beam_search_module = tf.load_op_library('../cpp/proj/TFWordBeamSearch.so')

# input with shape TxBxC
mat=tf.placeholder(tf.float32, shape=[None, None, None]) # we don't know the size yet, therefore we use [None, None, None]

# decode using the "Words" mode of word beam search with beam width set to 25 and add-k smoothing to 0.0
# !!!ONLY CALL ONCE IN YOUR PROGRAM!!!
decode=word_beam_search_module.word_beam_search(mat, 25, 'Words', 0.0, corpus, chars, wordChars)

# feed matrix of shape TxBxC and evaluate TF graph
data = loadData()
for feedMat in data:
	res=sess.run(decode, { mat:feedMat })
	# here you can do something with the result res
````

2. Regarding batch-decoding:
Even if your matrix sizes differ between samples, you could still make use of batch decoding: for each batch, search the largest matrix of size Tmax. 
Then, increase the size of all smaller matrices by inserting as much time-steps as needed until they also have Tmax time-steps.
Each inserted time-step must have a probability of 1 for the blank and 0 for all others (after softmax).
This way, these added time-steps are simply ignored while decoding.


Regards
Harry

**Comment by mmedinajiem** [comment]
Hi Harry.

Thank you for taking your time for the detailed explanation.

I see. Yeah, my case is the number 2: Each sample has different sizes (for time). I'll try what you suggest and I'll get back to you.

Regards!
Manuel

**Comment by githubharald** [comment]
any news about the memory leak?

**Comment by mmedinajiem** [comment]
Just finished implementing your suggestion number 2. I worked with batches of 100. Worked very nice and didn't see problems with memory. Thanks!

I'll try with different number of samples per batch. Is there a recommended max number to work with?

**Comment by githubharald** [comment]
no, it does not matter as it is single-threaded at the moment.
